### ISSUE TITLE
SpiffyTitles - FeedBurner on initial HTTP-Connect

### ISSUE THREAD

**Issue by fred0r** [oddluck/limnoria-plugins#23]
There seems to be a problem when a Link is pasted  with `http://`

`http://feeds.reuters.com/~r/Reuters/worldNews/~3/i8QnBIie36s/churchill-statue-boarded-up-ahead-of-expected-uk-protests-on-saturday-idUSKBN23J1LO`

But the URL gets rewritten to use http**s**

Console shows:
`SpiffyTitles HTTPError: 404 Client Error: Feed not found error: FeedBurner cannot locate this feed URI. for url: http://feeds.reuters.com/`

`SpiffyTitles: Unable to parse title from html response for https://feeds.reuters.com/`

Firefox with http**s**: `PR_END_OF_FILE_ERROR`

When entering the http-URL in Firefox, it gets redirected to 
`https://www.reuters.com/article/us-minneapolis-police-protests-britain/churchill-statue-boarded-up-ahead-of-expected-uk-protests-on-saturday-idUSKBN23J1LO?feedType=RSS&feedName=worldNews&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Reuters%2FworldNews+%28Reuters+World+News%29`

Another Example:
`http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/FSM2YM9SXNs/index.html`

**Comment by oddluck** [comment]
Thanks for the issue. The problem was the urlRegularExpression didn't allow for "~" in URLs. Fixed in the latest commit, however you will need to update the config yourself. Update/reload the plugin then send to your bot:

`config setdefault plugins.spiffytitles.urlregularexpression`

or manually update the config with:

`config plugins.spiffytitles.urlregularexpression "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+~]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"`

**Comment by fred0r** [comment]
Thank you
