### ISSUE TITLE
Tweety/SpiffyTitles - Twitter Events

### ISSUE THREAD

**Issue by fred0r** [oddluck/limnoria-plugins#27]
Bot isnt able to announce a 'Twitter-Event' URL - https://twitter.com/i/events/1272797478157299712 :

```
ERROR 2020-06-17T01:59:14 SpiffyTitles: Twitter Error: 404 Client Error: Not Found for url: https://publish.twitter.com/oembed?url=https://twitter.com/i/events/1272797478157299712&omit_script=True
ERROR 2020-06-17T01:59:14 SpiffyTitles: Unable to parse title from html response for https://twitter.com/i/events/1272797478157299712        
```

Bot just shows the default Errormsg in IRC.

**Comment by oddluck** [comment]
The oembed API endpoint that SpiffyTitles uses doesn't handle events and so would require authenticating to the full Twitter API. Support for this would be easier to add to Tweety since that already handles Twitter authentication. When i fix the Twitch handler it will require adding OAuth support, which will open the door to expanding this functionality to the Twitter handler as well.

**Comment by fred0r** [comment]
Would it be enough to set `supybot.plugins.SpiffyTitles.twitter.enabled` to `False` after enabling the Twitter-Plugin - or must the Twitter-Urls be also added to `supybot.plugins.SpiffyTitles.ignoredDomainPattern` ?

**Comment by oddluck** [comment]
Yes, if you don't want the default handler to handle those URLs either you'll need to set `ignoredDomainPattern`

**Comment by oddluck** [comment]
Twitter no longer offers free API access, plugin officially terminated.
